force-app/main/default/objects/Campaign/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Initiative</label>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <label>Initiative</label>
    <nameField>
        <label>Initiative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative__c/fields/ActiveMinimumToContinue__c.field-meta.xml
<CustomField>
    <fullName>ActiveMinimumToContinue__c</fullName>
    <label>Active Minimum To Continue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/ActiveParticipants__c.field-meta.xml
<CustomField>
    <fullName>ActiveParticipants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Participants</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/AddThreshhold__c.field-meta.xml
<CustomField>
    <fullName>AddThreshhold__c</fullName>
    <label>Add Threshhold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/DaysToPause__c.field-meta.xml
<CustomField>
    <fullName>DaysToPause__c</fullName>
    <label>Days To Pause</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Week 1</fullName>
            </value>
            <value>
                <fullName>Week 2</fullName>
            </value>
            <value>
                <fullName>Week 3</fullName>
            </value>
            <value>
                <fullName>Week 4</fullName>
            </value>
            <value>
                <fullName>Week 5</fullName>
            </value>
            <value>
                <fullName>Week 6</fullName>
            </value>
            <value>
                <fullName>Week 7</fullName>
            </value>
            <value>
                <fullName>Week 8</fullName>
            </value>
            <value>
                <fullName>Week 9</fullName>
            </value>
            <value>
                <fullName>Week 10</fullName>
            </value>
            <value>
                <fullName>Week 11</fullName>
            </value>
            <value>
                <fullName>Week 12</fullName>
            </value>
            <value>
                <fullName>Week 13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Repeats__c.field-meta.xml
<CustomField>
    <fullName>Repeats__c</fullName>
    <label>Repeats</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>StartTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/UseActiveMinimums__c.field-meta.xml
<CustomField>
    <fullName>UseActiveMinimums__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Active Minimums</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InitiativeEvent__c/InitiativeEvent__c.object-meta.xml
<CustomObject>
    <label>Initiative Event</label>
    <nameField>
        <label>InitiativeEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiative Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InitiativeEvent__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/InitiativeEvent__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <label>Initiative</label>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Initiative Events</relationshipLabel>
    <relationshipName>Initiative_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InitiativeEvent__c/fields/MaxSeats__c.field-meta.xml
<CustomField>
    <fullName>MaxSeats__c</fullName>
    <label>Max Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InitiativeEvent__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TL_BC_Tests.cls
@IsTest
public with sharing class TL_BC_Tests {
  @TestSetup
  static void makeData(){
    Google_Token__c token = new Google_Token__c(
      Access_Token__c = 'sada',
      Refresh_Token__c = 'dasd',
      Expires_In__c = System.today().addDays(1),
      Email__c = 'test@test.com'
    );

    Contact contact1 = new Contact(
      FirstName = 'Test',
      LastName = 'Contact 1',
      Email = 'email@test.com'
    );

    Initiative__c initiativeWeekly = new Initiative__c(
      Name = 'Test Initiative Weekly',
      AddThreshhold__c = 1,
      MaxSeats__c = 3,
      UseActiveMinimums__c = true,
      ActiveMinimumToContinue__c = 1,
      Email__c = 'test@test.com',
      DaysToPause__c = 1,
      StartTime__c = System.now(),
      Repeats__c = 'Weekly',
      Day__c = System.now().addDays(1).format('EEEE'),
      Frequency__c = 'Week 1',
      Duration__c = 30
    );

    Initiative__c initiativeMonthly = new Initiative__c(
      Name = 'Test Initiative Monthly',
      AddThreshhold__c = 1,
      MaxSeats__c = 3,
      UseActiveMinimums__c = true,
      ActiveMinimumToContinue__c = 1,
      Email__c = 'test@test.com',
      DaysToPause__c = 1,
      StartTime__c = System.now(),
      Repeats__c = 'Monthly',
      Day__c = System.now().addDays(1).format('EEEE'),
      Frequency__c = 'Week 1',
      Duration__c = 30
    );
    insert new List<sObject>{token, initiativeWeekly, initiativeMonthly, contact1};

    GoogleCalendar__c gc = new GoogleCalendar__c(
      Name = 'Test Calendar',
      GoogleId__c = 'sadas',
      GoogleToken__c = token.Id,
      Default__c = true
    );
    Campaign activeMonthly = new Campaign(Name = 'Test Campaign Monthly');
    Campaign activeWeekly = new Campaign(Name = 'Test Campaign Weekly');
    insert new List<sObject>{gc, activeWeekly, activeMonthly};

    initiativeWeekly.ActiveParticipants__c = activeWeekly.Id;
    initiativeMonthly.ActiveParticipants__c = activeMonthly.Id;
    update new List<sObject>{initiativeWeekly, initiativeMonthly};

    CampaignMember cmW = new CampaignMember(
      CampaignId = activeWeekly.Id,
      ContactId = contact1.Id,
      Status = 'Attended'
    );
    CampaignMember cmM = new CampaignMember(
      CampaignId = activeMonthly.Id,
      ContactId = contact1.Id,
      Status = 'Attended'
    );
    insert new List<sObject>{cmW, cmM};
  }

  @IsTest
  public static void automatedProcess_Test(){
    Initiative__c[] inits = [SELECT Id FROM Initiative__c];
    for(Initiative__c init: inits) TL_BC_ScheduledProcess.init(init.Id);
    for(Initiative__c init: inits) TL_BC_ScheduledProcess.init(init.Id);
  }

  @IsTest
  public static void scheduledProcess_Test(){
    Initiative__c[] inits = [SELECT Id FROM Initiative__c];
    try {
      TL_BC_ScheduledProcess.schedule(inits);
    } catch (Exception e) {}
  }

  @IsTest
  public static void iSeat_Test(){
    Google_Token__c token = [SELECT Id FROM Google_Token__c limit 1];
    Test.startTest();
    System.enqueueJob(new TL_BC_iSeat.addGuest('eventId', 'calendarId', new List<String>{'test@test.com'}, token));
    Test.stopTest();
  }

  @IsTest
  public static void iEventAttendanceClass_Test(){
    Google_Token__c[] tokens = [SELECT Id FROM Google_Token__c];
    Test.startTest();
    System.enqueueJob(new TL_BC_IEvent_Actions.UpdateAtt(tokens));
    Test.stopTest();
  }

  @IsTest
  public static void iEventAttendance_Test(){
    Google_Token__c token = [SELECT Id FROM Google_Token__c limit 1];
    GoogleCalendar__c gc = [SELECT Id FROM GoogleCalendar__c limit 1];
    Test.startTest();
    TL_BC_IEvent_Actions.updateAttendance(gc.Id, token.Id);
    Test.stopTest();
  }

  @IsTest
  public static void googleEventQueueCreate_Test(){
    Initiative__c inits = [SELECT Id FROM Initiative__c limit 1];
    InitiativeEvent__c event = new InitiativeEvent__c(
      Name = 'Test Event',
      Initiative__c = inits.Id,
      StartDate__c = System.now(),
      EndDate__c = System.now().addHours(1)
    );
    insert event;
    Google_Token__c token = [SELECT Id FROM Google_Token__c limit 1];
    GoogleCalendar__c gc = [SELECT Id FROM GoogleCalendar__c limit 1];
    Test.startTest();
    System.enqueueJob(new TL_BC_IEvent_Actions.GoogleEventQueue(event.Id, gc.Id, token.Id, 'CREATE'));
    Test.stopTest();
  }

  @IsTest
  public static void googleEventQueueDelete_Test(){
    Initiative__c inits = [SELECT Id FROM Initiative__c limit 1];
    InitiativeEvent__c event = new InitiativeEvent__c(
      Name = 'Test Event',
      Initiative__c = inits.Id,
      StartDate__c = System.now(),
      EndDate__c = System.now().addHours(1)
    );
    insert event;
    Google_Token__c token = [SELECT Id FROM Google_Token__c limit 1];
    GoogleCalendar__c gc = [SELECT Id FROM GoogleCalendar__c limit 1];
    Test.startTest();
    System.enqueueJob(new TL_BC_IEvent_Actions.GoogleEventQueue(event.Id, gc.Id, token.Id, 'DELETE'));
    Test.stopTest();
  }
}