force-app/main/default/objects/Initiative__c/Initiative__c.object-meta.xml
<CustomObject>
    <label>Initiative</label>
    <nameField>
        <label>Initiative Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiatives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Initiative__c/fields/ActiveMinimumToContinue__c.field-meta.xml
<CustomField>
    <fullName>ActiveMinimumToContinue__c</fullName>
    <label>Active Minimum To Continue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/ActiveMinimumToStart__c.field-meta.xml
<CustomField>
    <fullName>ActiveMinimumToStart__c</fullName>
    <label>Active Minimum To Start</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/ActiveParticipants__c.field-meta.xml
<CustomField>
    <fullName>ActiveParticipants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Participants</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Initiatives</relationshipLabel>
    <relationshipName>Initiatives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/AddThreshhold__c.field-meta.xml
<CustomField>
    <fullName>AddThreshhold__c</fullName>
    <label>Add Threshhold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/CurrentEvent__c.field-meta.xml
<CustomField>
    <fullName>CurrentEvent__c</fullName>
    <label>Current Event</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Day__c.field-meta.xml
<CustomField>
    <fullName>Day__c</fullName>
    <label>Day</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/DaysToPause__c.field-meta.xml
<CustomField>
    <fullName>DaysToPause__c</fullName>
    <label>Days To Pause</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/EventCount__c.field-meta.xml
<CustomField>
    <fullName>EventCount__c</fullName>
    <label>Event Count</label>
    <summaryForeignKey>InitiativeEvent__c.Initiative__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Week 1</fullName>
            </value>
            <value>
                <fullName>Week 2</fullName>
            </value>
            <value>
                <fullName>Week 3</fullName>
            </value>
            <value>
                <fullName>Week 4</fullName>
            </value>
            <value>
                <fullName>Week 5</fullName>
            </value>
            <value>
                <fullName>Week 6</fullName>
            </value>
            <value>
                <fullName>Week 7</fullName>
            </value>
            <value>
                <fullName>Week 8</fullName>
            </value>
            <value>
                <fullName>Week 9</fullName>
            </value>
            <value>
                <fullName>Week 10</fullName>
            </value>
            <value>
                <fullName>Week 11</fullName>
            </value>
            <value>
                <fullName>Week 12</fullName>
            </value>
            <value>
                <fullName>Week 13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/InactiveParticipants__c.field-meta.xml
<CustomField>
    <fullName>InactiveParticipants__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inactive Participants</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Initiatives (Inactive Participants)</relationshipLabel>
    <relationshipName>Initiatives1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/Repeats__c.field-meta.xml
<CustomField>
    <fullName>Repeats__c</fullName>
    <label>Repeats</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <label>StartTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Initiative__c/fields/UseActiveMinimums__c.field-meta.xml
<CustomField>
    <fullName>UseActiveMinimums__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Active Minimums</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/InitiativeEvent__c/InitiativeEvent__c.object-meta.xml
<CustomObject>
    <label>Initiative Event</label>
    <nameField>
        <label>InitiativeEvent Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initiative Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InitiativeEvent__c/fields/GoogleCalendarId__c.field-meta.xml
<CustomField>
    <fullName>GoogleCalendarId__c</fullName>
    <label>Google Calendar Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InitiativeEvent__c/fields/GoogleEventId__c.field-meta.xml
<CustomField>
    <fullName>GoogleEventId__c</fullName>
    <label>GoogleEventId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InitiativeEvent__c/fields/Initiative__c.field-meta.xml
<CustomField>
    <fullName>Initiative__c</fullName>
    <label>Initiative</label>
    <referenceTo>Initiative__c</referenceTo>
    <relationshipLabel>Initiative Events</relationshipLabel>
    <relationshipName>Initiative_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InitiativeEvent__c/fields/MaxSeats__c.field-meta.xml
<CustomField>
    <fullName>MaxSeats__c</fullName>
    <label>Max Seats</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InitiativeEvent__c/fields/Seats__c.field-meta.xml
<CustomField>
    <fullName>Seats__c</fullName>
    <label>Seats</label>
    <summaryForeignKey>InitiativeSeat__c.Initiative_Event__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/TL_BC_ScheduledProcess.cls
public class TL_BC_ScheduledProcess implements Schedulable {
  public static Id jobId;
  public Id initId;

  public TL_BC_ScheduledProcess(Id initId){
    this.initId = initId;
  }

	public void execute(SchedulableContext ctx) {
		init(this.initId);
	}

	public static void init(Id initId){
    Initiative__c init = [SELECT Id, Name, ActiveMinimumToContinue__c, Day__c, Repeats__c, Frequency__c, MaxSeats__c, AddThreshhold__c, InactiveParticipants__c, Duration__c, StartTime__c, DaysToPause__c, EventCount__c, CurrentEvent__c, UseActiveMinimums__c, ActiveMinimumToStart__c, ActiveParticipants__c FROM Initiative__c WHERE Id = :initId];
    InitiativeEvent__c[] initEvents = [SELECT Id, MaxSeats__c, Seats__c, Initiative__c, GoogleCalendarId__c, GoogleEventId__c FROM InitiativeEvent__c WHERE Initiative__c = :initId];
    for(InitiativeEvent__c initEvent: initEvents) TL_BC_AutomatedProcess.addInitiativeSeats(initEvent);
    TL_BC_AutomatedProcess.scheduleNextEvent(init);
    TL_BC_AutomatedProcess.checkCIH(new List<Initiative__c>{ init });
	}

  @InvocableMethod(label='Initiative Automation' description='Initiative Automation')
	public static void schedule(Initiative__c[] inits){
    Initiative__c init = inits[0];
		TL_BC_ScheduledProcess operation = new TL_BC_ScheduledProcess(init.Id);
    System.schedule('TL IE Initiative '+init.Name, '0 0 * * * ?', operation);
	}
}